// Auto-generated content metadata - do not edit manually
// Generated by scripts/generateContentImports.ts
// This file provides type-safe access to blog post metadata at build time

import type { SerializedPost } from '@/types/post'

// Processed blog posts with metadata only (content loaded lazily)
// Note: dates are serialized as ISO strings and must be converted to Date objects
export const processedPosts: SerializedPost[] = [
  {
    "title": "Why transition: all Is Risky (CSS Transition Pitfall)",
    "date": "2025-12-04T00:00:00.000Z",
    "description": "A small CSS bug caused by `transition: all`, and the subtle visual flicker it introduced—along with why explicitly scoping transitions leads to more predictable UI behavior.",
    "tags": [
      "css",
      "bugs",
      "debugging",
      "fix"
    ],
    "slug": "why-transition-all-is-risky",
    "topic": "css",
    "content": "",
    "readingTime": 3
  },
  {
    "title": "Fundamentals in Service of Growth: Learning New Frameworks",
    "date": "2025-12-22T00:00:00.000Z",
    "description": "A reflection on learning new frameworks while consulting full-time, and why staying grounded in fundamentals matters more than keeping up with every new tool.",
    "tags": [
      "learning",
      "productivity",
      "personal growth",
      "developer journey"
    ],
    "slug": "fundamentals-in-service-of-growth-learning-new-frameworks",
    "topic": "inkdrop",
    "content": "",
    "readingTime": 4
  },
  {
    "title": "Notes in Service of Doing: Choosing Inkdrop",
    "date": "2025-12-21T00:00:00.000Z",
    "description": "A reflection on choosing Inkdrop over Obsidian and Notion, and how deliberate constraints support clear thinking and consistent execution.",
    "tags": [
      "inkdrop",
      "note-taking",
      "developers",
      "productivity",
      "knowledge-management",
      "tools"
    ],
    "slug": "notes-in-service-of-doing-choosing-inkdrop",
    "topic": "inkdrop",
    "content": "",
    "readingTime": 5
  },
  {
    "title": "macOS Neovim 0.11+ Native LSP Configuration",
    "date": "2025-12-20T00:00:00.000Z",
    "description": "Step by step guide on how I setup LSP in Neovim 0.11+ in macOS.",
    "tags": [
      "vim",
      "neovim",
      "lsp",
      "configuration"
    ],
    "slug": "native-lsp-setup-in-neovim-0.11+-on-macos",
    "topic": "neovim",
    "content": "",
    "readingTime": 5
  },
  {
    "title": "Build-Time Content Generation",
    "date": "2025-12-24T00:00:00.000Z",
    "description": "A deep dive into my custom build-time content processing system that transforms markdown files into type-safe TypeScript modules, including the trade-offs and design decisions.",
    "tags": [
      "build-tools",
      "typescript",
      "markdown",
      "performance",
      "developer-experience",
      "content-management"
    ],
    "slug": "build-time-content-generation",
    "topic": "tools",
    "content": "",
    "readingTime": 6
  },
  {
    "title": "Learning TypeScript Through Constraints, Not Tutorials",
    "date": "2025-12-23T00:00:00.000Z",
    "description": "How I approach learning TypeScript as a JavaScript developer by starting with strict tooling and letting constraints guide my understanding.",
    "tags": [
      "typescript",
      "tooling",
      "learning",
      "developer-experience",
      "personal-growth"
    ],
    "slug": "learning-typescript-through-constraint-not-tutorials",
    "topic": "typescript",
    "content": "",
    "readingTime": 5
  },
  {
    "title": "A Journey into Full-Stack Development: Exploring a pnpm Workspace Monorepo",
    "date": "2025-12-29T00:00:00.000Z",
    "description": "A hands-on look at setting up a pnpm workspace monorepo for Yaru Koto, including shared packages, TypeScript types, and full-stack project structure for solo developers.",
    "tags": [
      "pnpm",
      "monorepo",
      "workspace",
      "full-stack",
      "web-development"
    ],
    "slug": "exploring-pnpm-workspace-monorepo",
    "topic": "web-development",
    "content": "",
    "readingTime": 9
  },
  {
    "title": "Implementing Dynamic Favicons",
    "date": "2025-12-25T00:00:00.000Z",
    "description": "A comprehensive exploration of building a theme-aware favicon system that adapts to both user preferences and system settings, including performance optimizations, browser compatibility considerations, and architectural trade-offs.",
    "tags": [
      "web-development",
      "accessibility",
      "performance",
      "browser-api",
      "theme-system",
      "typescript",
      "user-experience"
    ],
    "slug": "implementing-dynamic-favicons",
    "topic": "web-development",
    "content": "",
    "readingTime": 8
  },
  {
    "title": "Security-First Markdown Processing",
    "date": "2025-12-27T00:00:00.000Z",
    "description": "A deep dive into my restrictive markdown sanitization approach that prioritizes security while maintaining rich content features, exploring the trade-offs and implementation details.",
    "tags": [
      "security",
      "markdown",
      "web-development",
      "sanitization",
      "content-security",
      "unified",
      "rehype"
    ],
    "slug": "security-first-markdown-processing",
    "topic": "web-development",
    "content": "",
    "readingTime": 7
  },
  {
    "title": "What 2025 Taught Me as a Frontend Developer",
    "date": "2026-01-03T00:00:00.000Z",
    "description": "A personal reflection on my 2025 frontend journey—navigating growth, setbacks, and lessons learned from building, refactoring, and rethinking how I approach development.",
    "tags": [
      "frontend",
      "web-development",
      "react",
      "typescript",
      "dev-journey",
      "growth",
      "reflection",
      "career"
    ],
    "slug": "what-2025-taught-me-as-frontend-developer",
    "topic": "web-development",
    "content": "",
    "readingTime": 4
  },
  {
    "title": "My WezTerm Terminal Setup",
    "date": "2025-12-05T00:00:00.000Z",
    "description": "How I tuned my terminal for long, focused coding sessions by reducing visual noise and prioritizing ergonomics.",
    "tags": [
      "wezterm",
      "terminal",
      "productivity",
      "setup"
    ],
    "slug": "wezterm-terminal-setup",
    "topic": "wezterm",
    "content": "",
    "readingTime": 3
  }
] as const
